### ISSUE TITLE
Do a Better Job assuring we aren't swallowing unhandled exceptions during callbacks

### ISSUE THREAD

**Issue by bwmcadams** [bwmcadams/hammersmith#25]

**Comment by havocp** [comment]
I've explored this some while trying to adjust the API to remove RequestFuture. I came up with two options. One is to make the callbacks take an Either[Throwable, T] instead of a T. The other is to leave the callbacks taking just T, but to have an error callback also. The error callback could default to one set on the collection/db/connection, similar to how the WriteConcern works, and the default error callback could just log errors. Anyway, those are my two ideas. It's sort of a "checked vs. unchecked exceptions" kind of religious judgment call, really.

**Comment by bwmcadams** [comment]
Don't the callbacks already take Either[Throwable, T]?  We just have some "simple" implicits that let you call them without the Either.

**Comment by bwmcadams** [comment]
This is an obviated issue due to the rewrites.
